### ISSUE TITLE
DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`

### ISSUE THREAD

**Issue by zhmzm** [locuslab/open-unlearning#38]
Hi,

Thanks for sharing the code and models.

I run the following command
```
master_port=18765
split=forget10
model=llama2-7b
lr=2e-5
CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=$master_port forget.py --config-name=forget.yaml split=${split} batch_size=4 gradient_accumulation_steps=4 model_family=${model} lr=${lr}
```

Then I encounter the following issue
```
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/tofu/forget.py", line 145, in main
    model = AutoModelForCausalLM.from_pretrained(model_id, use_flash_attention_2=model_cfg["flash_attention2"]=="true", torch_dtype=torch.bfloat16, device_map=device_map)
  File "/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/python3.10/site-packages/transformers/modeling_utils.py", line 3195, in from_pretrained
    raise ValueError(
ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.

```

**Comment by zhilif** [comment]
Hi. Can you try to comment out "device_map" when initializing the model?

**Comment by Dornavineeth** [comment]
Hello, we've updated the TOFU codebase to [OpenUnlearning](https://github.com/locuslab/open-unlearning), an easy-to-use framework for experimentation supporting multiple unlearning benchmarks (including TOFU and MUSE). Check out the latest documentation for usage details and the new target base models and retain models on [HuggingFace](https://huggingface.co/open-unlearning) across 1B to 8B sizes.
We'd love to hear your feedback and welcome any contributions to the repository!
